export const thundercat = [
    {
        id: '1',
        name: 'Lion-O',
        image: '../assets/lion-o.jpg',
        description: 'Intrepid leader and guiding light.',
        category: '-Leader-',
        isReal: false,
        color: 'lightblue',
        cost: 50.00,
    },

    {
        id: '2',
        name: 'Cheetara',
        image: '../assets/cheetara.jpg',
        description: 'Indomintable and fast.',
        category: '-Runner-',
        isReal: false,
        color: 'orange',
        cost: 45.00,
    },

    {
        id: '3',
        name: 'Panthero',
        image: '../assets/panthero.jpg',
        description: 'Resourceful and strong.',
        category: '-Engineer-',
        isReal: false,
        color: 'cornflowerblue',
        cost: 42.50,
    },
    {
        id: '4',
        name: 'Snarf',
        image: '../assets/snarf.jpg',
        description: 'Cowardly comedic relief.',
        category: '-Pet-',
        isReal: false,
        color: 'red',
        cost: 35,
    },
    {
        id: '5',
        name: 'Thundercat',
        image: '../assets/thundercat.jpg',
        description: 'Phenominal bass player.',
        category: '-Musician-',
        isReal: true,
        color: 'pink',
        cost: 1000000,
    },
];